worker_processes  1;
worker_rlimit_nofile 1024;
events {
    worker_connections  800;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    index         index.html index.htm;
    keepalive_timeout  65;
    server_tokens off;
    server {
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name arkgate.local;
        location / {
                try_files $uri $uri/ =404;
        }
        location /api {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_pass http://127.0.0.1:44444;
        }
        location /ui {
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_pass http://127.0.0.1:8000;
        }
        listen [::]:443 ssl ipv6only=on; # managed by Certbot
        listen 443 ssl; # managed by Certbot
        ssl_certificate /usr/loca/arkgate/ssl/cert.pem; # managed by acme-client
        ssl_certificate_key /usr/local/arkgate/ssl/private/key.pem; # managed by acme-client
    }
}